-- Foundation helpers shared by every tenant table.
-- Conventions (see docs/adr/0006-tenancy-rls-and-db-roles.md):
--   * every tenant table has tenant_id, ENABLE + FORCE row level security and a
--     tenant_isolation policy on current_tenant_id();
--   * every index on a tenant table starts with tenant_id;
--   * foreign keys between tenant tables include tenant_id;
--   * ids are UUID v7 generated by the client; the database checks the version;
--   * the app role (autoparts_app) never gets DELETE or TRUNCATE.

-- The tenant of the current transaction, set with
--   SELECT set_config('app.tenant_id', '<uuid>', true)   -- i.e. SET LOCAL
-- Returns NULL when unset, so policies match no rows (fail closed).
CREATE FUNCTION current_tenant_id() RETURNS uuid
  LANGUAGE sql STABLE PARALLEL SAFE
  AS $$ SELECT nullif(pg_catalog.current_setting('app.tenant_id', true), '')::uuid $$;

CREATE FUNCTION is_uuid_v7(value uuid) RETURNS boolean
  LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
  AS $$
    SELECT substr(value::text, 15, 1) = '7'
       AND substr(value::text, 20, 1) IN ('8', '9', 'a', 'b')
  $$;

-- Guard for append-only tables. Fires even for the owner role.
CREATE FUNCTION forbid_mutation() RETURNS trigger
  LANGUAGE plpgsql
  AS $$
  BEGIN
    RAISE EXCEPTION '% on % is not allowed: table is append-only', TG_OP, TG_TABLE_NAME
      USING ERRCODE = 'restrict_violation';
  END
  $$;

CREATE FUNCTION set_updated_at() RETURNS trigger
  LANGUAGE plpgsql
  AS $$
  BEGIN
    NEW.updated_at := now();
    RETURN NEW;
  END
  $$;

-- Locale tags such as 'ar', 'en', 'ar-EG'. Which locales a tenant uses is configuration.
CREATE FUNCTION is_locale_tag(value text) RETURNS boolean
  LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT value ~ '^[a-z]{2,3}(-[A-Z]{2})?$' $$;
