/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuditLog {
  action: string;
  actor_user_id: string | null;
  after: Json | null;
  before: Json | null;
  device_id: string | null;
  entity_id: string | null;
  entity_type: string;
  id: string;
  occurred_at: Generated<Timestamp>;
  reason: string | null;
  recorded_at: Generated<Timestamp>;
  request_id: string | null;
  tenant_id: string;
}

export interface Brands {
  archived_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  id: string;
  kind: string;
  name: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Categories {
  archived_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  id: string;
  name_ar: string | null;
  name_en: string | null;
  parent_id: string | null;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Devices {
  created_at: Generated<Timestamp>;
  created_by: string;
  credential_hash: Buffer | null;
  enrolled_at: Timestamp | null;
  enrollment_code_hash: Buffer | null;
  enrollment_expires_at: Timestamp | null;
  id: string;
  last_seen_at: Timestamp | null;
  location_id: string | null;
  name: string;
  revoked_at: Timestamp | null;
  revoked_by: string | null;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Fitments {
  created_at: Generated<Timestamp>;
  id: string;
  note: string | null;
  part_id: string;
  removed_at: Timestamp | null;
  supersession_id: string | null;
  tenant_id: string;
  vehicle_id: string;
}

export interface FxRates {
  base_currency: string;
  id: string;
  note: string | null;
  quote_currency: string;
  rate: Numeric;
  rate_date: Timestamp;
  recorded_at: Generated<Timestamp>;
  recorded_by: string;
  tenant_id: string;
}

export interface ImportBatches {
  applied_at: Timestamp | null;
  applied_by: string | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  file_name: string;
  file_sha256: Buffer;
  header_row: number | null;
  id: string;
  kind: string;
  mapping: Generated<Json>;
  sheet_name: string | null;
  stats: Generated<Json>;
  status: Generated<string>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface ImportRows {
  batch_id: string;
  created_at: Generated<Timestamp>;
  decision: string | null;
  id: string;
  issues: Generated<string[]>;
  parsed: Generated<Json>;
  part_id: string | null;
  raw: Json;
  row_key: string | null;
  row_number: number;
  skipped_by_user: Generated<boolean>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface InterchangeGroups {
  created_at: Generated<Timestamp>;
  id: string;
  note: string | null;
  tenant_id: string;
}

export interface InterchangeMembers {
  created_at: Generated<Timestamp>;
  group_id: string;
  id: string;
  part_id: string;
  removed_at: Timestamp | null;
  tenant_id: string;
}

export interface LedgerQueue {
  created_at: Generated<Timestamp>;
  document_id: string;
  event: string;
  id: string;
  payload: Json;
  tenant_id: string;
}

export interface Locations {
  archived_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  id: string;
  is_default: Generated<boolean>;
  kind: string;
  name: string;
  sort_order: Generated<number>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface OpeningStockDrafts {
  as_of: Timestamp;
  batch_id: string;
  cost_currency: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  fx_rate_id: string | null;
  id: string;
  location_id: string;
  posted_at: Timestamp | null;
  posted_by: string | null;
  status: Generated<string>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface OpeningStockLines {
  amount: Numeric | null;
  cost_source: string | null;
  draft_id: string;
  exclusion: string | null;
  file_cost_total: Numeric | null;
  file_quantity: Numeric | null;
  part_id: string;
  quantity: number | null;
  rows: number;
  status: Generated<string | null>;
  suggested_unit_cost: Numeric | null;
  tenant_id: string;
  unit_cost: Numeric | null;
  updated_at: Generated<Timestamp>;
}

export interface PartNumbers {
  brand_id: string | null;
  created_at: Generated<Timestamp>;
  id: string;
  kind: string;
  number: string;
  number_norm: Generated<string | null>;
  part_id: string;
  removed_at: Timestamp | null;
  tenant_id: string;
}

export interface PartPrices {
  effective_at: Timestamp;
  id: string;
  import_batch_id: string | null;
  part_id: string;
  price: Numeric;
  price_list_id: string;
  reason: string | null;
  recorded_at: Generated<Timestamp>;
  recorded_by: string | null;
  source: string;
  tenant_id: string;
}

export interface Parts {
  archived_at: Timestamp | null;
  brand_id: string | null;
  category_id: string | null;
  created_at: Generated<Timestamp>;
  id: string;
  name_ar: string | null;
  name_en: string | null;
  notes: string | null;
  quality_grade: string | null;
  search_text: Generated<string | null>;
  sku: string;
  sku_norm: Generated<string | null>;
  tenant_id: string;
  unit: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface PriceLists {
  archived_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  currency: string;
  id: string;
  is_default: Generated<boolean>;
  name: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Roles {
  archived_at: Timestamp | null;
  code: string;
  created_at: Generated<Timestamp>;
  id: string;
  is_system: Generated<boolean>;
  name: string;
  permissions: Generated<string[]>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Sessions {
  created_at: Generated<Timestamp>;
  device_id: string | null;
  expires_at: Timestamp;
  id: string;
  ip: string | null;
  last_seen_at: Generated<Timestamp>;
  revoked_at: Timestamp | null;
  revoked_reason: string | null;
  secret_hash: Buffer;
  tenant_id: string;
  user_agent: string | null;
  user_id: string;
}

export interface StockBalances {
  last_in_at: Timestamp | null;
  last_out_at: Timestamp | null;
  location_id: string;
  part_id: string;
  quantity: Generated<number>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface StockCosts {
  last_move_id: string | null;
  part_id: string;
  quantity: Generated<number>;
  ref_quantity: number | null;
  ref_value: Numeric | null;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  value: Generated<Numeric>;
}

export interface StockCountLines {
  count_id: string;
  counted: number | null;
  counted_at: Timestamp | null;
  counted_by: string | null;
  expected: number | null;
  part_id: string;
  tenant_id: string;
}

export interface StockCounts {
  category_id: string | null;
  closed_at: Timestamp | null;
  closed_by: string | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  document_id: string | null;
  id: string;
  location_id: string;
  note: string | null;
  scope: string;
  status: Generated<string>;
  tenant_id: string;
}

export interface StockDocuments {
  device_id: string | null;
  id: string;
  kind: string;
  note: string | null;
  occurred_at: Timestamp;
  origin: string;
  posted_at: Generated<Timestamp>;
  posted_by: string;
  request_hash: Buffer;
  tenant_id: string;
}

export interface StockMoves {
  amount: Numeric;
  cost_known: Generated<boolean>;
  currency: string;
  document_id: string;
  functional_amount: Numeric;
  fx_base: string;
  fx_quote: string;
  fx_rate: Numeric;
  fx_rate_id: string | null;
  id: string;
  kind: string;
  line_no: number;
  location_id: string | null;
  occurred_at: Timestamp;
  part_id: string;
  prev_location_quantity: number | null;
  prev_part_quantity: number;
  prev_part_value: Numeric;
  quantity: number;
  reason: string | null;
  recorded_at: Generated<Timestamp>;
  seq: Generated<Int8>;
  tenant_id: string;
}

export interface StockReviewItems {
  id: string;
  kind: string;
  location_id: string | null;
  move_id: string;
  opened_at: Generated<Timestamp>;
  part_id: string;
  resolution_document_id: string | null;
  resolution_note: string | null;
  resolved_at: Timestamp | null;
  resolved_by: string | null;
  tenant_id: string;
}

export interface Supersessions {
  created_at: Generated<Timestamp>;
  created_by: string;
  effective_at: Timestamp;
  id: string;
  new_part_id: string;
  old_part_id: string;
  reason: string | null;
  removed_at: Timestamp | null;
  tenant_id: string;
}

export interface TenantCurrencies {
  cash_increment: Numeric | null;
  code: string;
  created_at: Generated<Timestamp>;
  id: string;
  is_active: Generated<boolean>;
  minor_units: number;
  sort_order: Generated<number>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface TenantDirectory {
  archived: boolean;
  slug: string;
  tenant_id: string;
}

export interface Tenants {
  archived_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  default_locale: string;
  functional_currency: string;
  id: string;
  name: string;
  settings: Generated<Json>;
  slug: string;
  timezone: string;
  updated_at: Generated<Timestamp>;
}

export interface UserRoles {
  granted_at: Generated<Timestamp>;
  granted_by: string | null;
  id: string;
  revoked_at: Timestamp | null;
  revoked_by: string | null;
  role_id: string;
  tenant_id: string;
  user_id: string;
}

export interface Users {
  archived_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  display_name: string;
  email: string | null;
  failed_login_count: Generated<number>;
  id: string;
  last_login_at: Timestamp | null;
  locale: string | null;
  locked_until: Timestamp | null;
  password_changed_at: Timestamp | null;
  password_hash: string | null;
  pin_hash: string | null;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  username: string;
}

export interface VehicleAliases {
  alias: string;
  alias_norm: Generated<string | null>;
  category_id: string | null;
  created_at: Generated<Timestamp>;
  id: string;
  removed_at: Timestamp | null;
  target: string;
  tenant_id: string;
  vehicle_id: string | null;
}

export interface Vehicles {
  archived_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  displacement_cc: number | null;
  engine_code: string | null;
  fuel: string | null;
  id: string;
  level: string;
  name: string;
  name_ar: string | null;
  parent_id: string | null;
  search_text: Generated<string | null>;
  tenant_id: string | null;
  updated_at: Generated<Timestamp>;
  year_from: number | null;
  year_to: number | null;
}

export interface DB {
  audit_log: AuditLog;
  brands: Brands;
  categories: Categories;
  devices: Devices;
  fitments: Fitments;
  fx_rates: FxRates;
  import_batches: ImportBatches;
  import_rows: ImportRows;
  interchange_groups: InterchangeGroups;
  interchange_members: InterchangeMembers;
  ledger_queue: LedgerQueue;
  locations: Locations;
  opening_stock_drafts: OpeningStockDrafts;
  opening_stock_lines: OpeningStockLines;
  part_numbers: PartNumbers;
  part_prices: PartPrices;
  parts: Parts;
  price_lists: PriceLists;
  roles: Roles;
  sessions: Sessions;
  stock_balances: StockBalances;
  stock_costs: StockCosts;
  stock_count_lines: StockCountLines;
  stock_counts: StockCounts;
  stock_documents: StockDocuments;
  stock_moves: StockMoves;
  stock_review_items: StockReviewItems;
  supersessions: Supersessions;
  tenant_currencies: TenantCurrencies;
  tenant_directory: TenantDirectory;
  tenants: Tenants;
  user_roles: UserRoles;
  users: Users;
  vehicle_aliases: VehicleAliases;
  vehicles: Vehicles;
}
